### ISSUE TITLE
Raise more specfic exceptions

### ISSUE THREAD

**Issue by shuttle1987** [Surrerstry/distributed_containers#1]
Currently there are places in the code where the `Exception` class is being used directly. This makes it very hard for people to use your library as they will have to catch exceptions that are far too broad, something that generally speaking is undesirable.

For example:

https://github.com/Surrerstry/distributed_containers/blob/9d7d04bd698c97357276b28dc54f77d930da11c1/distributed_containers/distributed_containers.py#L144
```python
                if isinstance(container, list):
			self.container_type = 'list'
		elif isinstance(container, tuple):
			self.container_type = 'tuple'
		else:
                        raise Exception("Incorrect type of container: ({}), expected: 'list' or 'tuple'.".format(type(container)))
```
This would be much better if it were a `TypeError`

Likewise:
```python
if workers is not None and workers < 2:
    raise Exception('Amount of workers cannot be lower than 2')
```
Would be much better as a `ValueError`.

This way people can catch just the exceptions that they need to catch.

**Comment by Surrerstry** [comment]
Hi,

Thanks for tip, I'll change it in next version(In few days probably).

Regards

**Comment by Surrerstry** [comment]
Done, there are no more general exceptions.
